[WIP] Working on a build script for vector_add
nlesc-recruit/cudawrappers pull request #123
Opened 2022-03-04 09:48 UTC by abelsiqueira

**Description**

[WIP] Working on a build script for vector_add

**Related issues**:

- #116

**Instructions to review the pull request**

- Check that CHANGELOG.md has been updated if necessary

Clone and verify
```
cd $(mktemp -d --tmpdir cudawrappers-XXXXXX)
git clone https://github.com/nlesc-recruit/cudawrappers .
git checkout <this-branch>
cmake -S . -B build
make -C build
make -C build vector_add
make -C build format # Nothing should change
make -C build lint # linting is broken until we fix the issues (see #92)
```

2022-03-04 10:28 UTC, abelsiqueira commented
I have started a discussion on #116 which is blocking this.

2022-03-07 15:01 UTC, fdiblen commented on tests/CMakeLists.txt
> +)
```suggestion
)

```

2022-03-07 15:07 UTC, fdiblen commented on README.dev.md
>  ## Running the tests
```suggestion
## Running the tests on DAS
```

2022-03-07 15:08 UTC, fdiblen commented on README.dev.md
> +If you are running the tests on DAS, you can send create a job with command using `srun`.
```suggestion
If you are running the tests on DAS, you can run a job using `srun` command.
```

2022-03-07 15:09 UTC, fdiblen commented on README.dev.md
This command will run the tests in one of the worker nodes with a GPU device.

2022-03-07 15:40 UTC, fdiblen commented on README.dev.md
```suggestion
This command will run the tests in one of the worker nodes with a GPU device.
```

2022-03-07 15:41 UTC, fdiblen requested changes
Looks great! I made a few suggestions.

2022-03-07 15:48 UTC, fdiblen approved these changes
Thanks @abelsiqueira :cookie:

2022-03-07 15:49 UTC, abelsiqueira commented
Thanks for the review :broccoli:

2022-03-07 15:49 UTC, merged