Add cufft library
nlesc-recruit/cudawrappers pull request #151
Opened 2022-04-14 20:54 UTC by bouweandela

**Description**

**Related issues**:

- ...

**Instructions to review the pull request**

- Check that CHANGELOG.md has been updated if necessary

2022-04-20 11:24 UTC, csbnw commented
There are many Codacy suggestions for the code (the `cufft.*` files), these should either be addressed in this PR, or in a new issue.

2022-06-17 14:44 UTC, csbnw commented on include/cufft.hpp
> +                                     &neededWorkSize, CUDA_C_16F));
I don't think it's correct to use hard-coded `CUDA_C_16F` here.

2022-06-17 14:45 UTC, csbnw commented on include/cufft.hpp
> +          unsigned DIM = 1>
In it's current state, it doesn't seem like 2D FFTs are supported.

2022-06-17 14:47 UTC, csbnw commented on src/cufft.cpp
> +}
Isn't it safer to use an enum here, like [so](https://github.com/NVIDIA/cuda-samples/blob/b312abaa07ffdc1ba6e3d44a9bc1a8e89149c20b/Common/helper_cuda.h#L108)?

2022-07-08 12:38 UTC, john-romein commented on src/cufft.cpp
> +}
It used to be implemented as a large switch statement, but this is not strictly necessary as NVIDIA documents the error numbers (not just the names) in the manual.

2023-05-25 15:47 UTC, bouweandela commented on src/cufft.cpp
> +}
One of the linters complained about that, that's why I changed it. I can't quite remember what the complaint was though, since it is some time ago.

2023-06-23 12:31 UTC, csbnw commented on tests/convolution/convolution.cpp
> +  std::cout << "HERE WE ARE";
```suggestion
```

2023-06-23 12:32 UTC, csbnw commented on tests/convolution/convolution.cpp
> +
This function isn't used (anymore), please consider removing it:
```suggestion
```

2023-06-23 12:35 UTC, csbnw commented on tests/convolution/convolution.cpp
> +  cu::Stream my_stream;
Rename to `stream`, like in the other examples/tests?
```suggestion
  cu::Stream stream;
```

2023-06-29 13:06 UTC, csbnw commented on include/cufft.hpp
> +                                     &neededWorkSize, CUDA_C_16F));
This is fixed in the latest version.

2023-06-29 13:10 UTC, csbnw commented on tests/CMakeLists.txt
> +  target_link_libraries(test_${component} PUBLIC ${LINK_${component}} tests)
@bouweandela , you changed these lines, but I am not sure why this was needed specifically for the new `test_cufft`.

2023-06-29 13:28 UTC, matmanc commented on tests/CMakeLists.txt
> +  target_link_libraries(test_${component} PUBLIC ${LINK_${component}} tests)
I think because more then one library is used by cufft in particular it needs both cu an cufft

2023-06-29 13:28 UTC, csbnw commented on include/cudawrappers/cufft.hpp
> +      other.plan_ = 0;
According to `cufft.h`:
```
// cufftHandle is a handle type used to store and access CUFFT plans.
typedef int cufftHandle;
```
So `0` as it currently is seems appropriate.

2023-06-29 13:32 UTC, matmanc commented on include/cudawrappers/cufft.hpp
> +      other.plan_ = 0;
In the docs it says https://docs.nvidia.com/cuda/cufft/index.html?highlight=cufftHandle#cuffthandle
typedef unsigned int cufftHandle;
weird

2023-07-20 13:23 UTC, loostrum requested changes
I've left some minor comments, but overall it looks good to me! I'm not very familiar with cufft itself, so I'm assuming that the actual functionality is correct. Glad to see the tests passing at least. In addition to the few requested changes, could you also update the changelog file?

2023-07-20 13:23 UTC, loostrum commented on examples/vector_add/CMakeLists.txt
> +)
Is there a reason cudart is now linked here? The vector_add example runs fine on the main branch as well

2023-07-20 13:23 UTC, loostrum commented on include/cudawrappers/cufft.hpp
> +static const char *_cudaGetErrorEnum(cufftResult error) {
Is it necessary to have both the anonymous namespace and `static` declaration? I'm not too familiar with using them like this, but as far as I know they have the same purpose.

2023-07-20 13:23 UTC, loostrum commented on tests/CMakeLists.txt
> +  add_executable(test_${component} test_${component}.cpp)
Isn't the addition of the cpp file here duplicate with the next line?

2023-07-20 13:23 UTC, loostrum commented on tests/test_cufft.cpp
> +
This first empty line should be removed.

2023-07-20 14:55 UTC, csbnw commented on examples/vector_add/CMakeLists.txt
> +)
I am not sure why/when this was introduced, but I will revert it.

2023-07-20 14:56 UTC, csbnw commented on include/cudawrappers/cufft.hpp
> +static const char *_cudaGetErrorEnum(cufftResult error) {
It indeed seems like we don't need the anonymous namespace here.

2023-07-20 15:00 UTC, csbnw commented on tests/test_cufft.cpp
> +
:heavy_check_mark:

2023-07-20 15:50 UTC, loostrum approved these changes

2023-07-21 07:41 UTC, merged